server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: address-service
        uri: lb://address-service
        predicates[0]: Path=/api/product
      routes[1]:
        id: employee-service
        uri: lb://employee-service
        predicates[0]: Path=/api/employee
      routes[2]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[3]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
